from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Iterator

from rules.models import AutomationLevel, QcIssue, Severity

# 脱敏规则字典 fixture（与桌面 xlsx 结构一致）
RULE_DICTIONARY_CSV = (
    Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "rule_dictionary_sanitized.csv"
)


class ImplementationStatus(str, Enum):
    IMPLEMENTED = "implemented"
    PLANNED = "planned"
    MANUAL_ONLY = "manual_only"


class AgentPriority(str, Enum):
    """Agent 开发排期（与字典「实施优先级」人工轨道分开）。

    当前 P1 = M2a：整底稿流水线 + 汇总/K.01 优先；非 FA list 规则扩张。
    """
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    MANUAL = "MANUAL"


@dataclass(frozen=True)
class RuleSpec:
    """规则字典条目 + Agent 映射元数据。"""

    dict_code: str
    rule_id: str
    rule_name: str
    procedure_code: str
    sheet_hints: tuple[str, ...]
    automation: AutomationLevel
    default_severity: Severity
    problem_category: str
    reviewer_role: str  # preparer | reviewer
    qc_checkpoint: str
    k1_ref: str
    sheet_kinds: tuple[str, ...] = ()
    manual_priority: str | None = None  # 字典实施优先级：P1-最高 等
    agent_priority: AgentPriority = AgentPriority.MANUAL
    implementation: ImplementationStatus = ImplementationStatus.PLANNED
    notes: str = ""

    def enrich_issue(self, issue: QcIssue) -> QcIssue:
        """将注册表元数据写入 QcIssue（不覆盖已有 message/suggestion）。"""
        issue.dict_rule_code = self.dict_code
        issue.rule_name = self.rule_name
        issue.problem_category = self.problem_category
        issue.reviewer_role = self.reviewer_role
        issue.qc_checkpoint = self.qc_checkpoint
        issue.automation_level = self.automation.value
        issue.k1_checklist_ref = self.k1_ref
        if issue.procedure_code == "FA_LIST" and self.procedure_code != "FA_LIST":
            issue.procedure_code = self.procedure_code
        return issue


def _specs() -> list[RuleSpec]:
    """内置规则注册表（来源：脱敏规则字典 + qc-checklist 补充）。"""
    return [
        # --- 底稿范围、程序设计 ---
        RuleSpec(
            dict_code="AE-001",
            rule_id="materiality_consistency",
            rule_name="PM/TE/SAD一致性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第5条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="摘录 PM/TE/SAD 至报告 manual_review_sections；Canvas 人工比对",
        ),
        RuleSpec(
            dict_code="LEAD-001",
            rule_id="lead_required_fields",
            rule_name="Lead 基准信息必填",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="qc-checklist K.00 基础信息",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="客户名称、期末、分析日期、TE、SAD、准则、币种",
        ),
        RuleSpec(
            dict_code="LEAD-002",
            rule_id="lead_analysis_date_after_period_end",
            rule_name="Lead 分析日期晚于期末",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="qc-checklist K.00 分析日期",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="分析日期须晚于资产负债表日；无法解析日期时为 WARN",
        ),
        RuleSpec(
            dict_code="LEAD-003",
            rule_id="lead_tt_overall_min",
            rule_name="Lead 整体TT等于认定TT最小值",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块2",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-004",
            rule_id="lead_tt_gam_range",
            rule_name="Lead 认定TT在GAM区间",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块2 GAM",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-005",
            rule_id="lead_expectation_analysis",
            rule_name="Lead 预期分析块完整",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块3",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-006",
            rule_id="lead_volatility_threshold_link",
            rule_name="Lead 波动金额link TT/TE",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块3",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-012",
            rule_id="lead_expectation_semantic",
            rule_name="Lead 预期分析语义充分性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块3（LLM语义增强）",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="仅在 --llm 启用时输出语义复核结果；不覆盖确定性规则结论",
        ),
        RuleSpec(
            dict_code="LEAD-013",
            rule_id="lead_fluctuation_notes_semantic",
            rule_name="Lead 异常波动说明语义充分性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块5（LLM语义增强）",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="仅评估“已填写说明”的语义充分性；空说明由确定性规则处理",
        ),
        RuleSpec(
            dict_code="LEAD-014",
            rule_id="lead_expectation_basis_present",
            rule_name="Lead 预期分析依据完整性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块3",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="弱规则：预期分析为空或仅为简短结论时提示补充判断依据。",
        ),
        RuleSpec(
            dict_code="LEAD-015",
            rule_id="lead_expectation_vs_movement_review",
            rule_name="Lead 预期与实际波动复核",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块3/5",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="当预期为无重大变化但主表波动超过阈值时，提示人工复核。",
        ),
        RuleSpec(
            dict_code="LEAD-016",
            rule_id="lead_fluctuation_notes_refs",
            rule_name="Lead Notes 编号与波动说明一致",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块5",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="检查 Lead 主表 Notes 引用与波动说明区编号是否能弱匹配。",
        ),
        RuleSpec(
            dict_code="LEAD-017",
            rule_id="lead_adjustment_internal_consistency",
            rule_name="Lead 调整事项内部一致性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险",
            k1_ref="lead-qc-rules 模块6",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes=(
                "主表调整列与调整汇总表；合计比对受 LLM 版式/跨科目门控（见 lead-adjustment-llm-design.md）。"
            ),
        ),
        RuleSpec(
            dict_code="LEAD-018",
            rule_id="lead_adjustment_layout_review",
            rule_name="Lead 调整汇总表版式识别",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险",
            k1_ref="lead-qc-rules 模块6",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="LLM：中英文表头、单列/借贷双列、符号约定；低置信不跑 LEAD-017 合计。",
        ),
        RuleSpec(
            dict_code="LEAD-019",
            rule_id="lead_adjustment_semantic",
            rule_name="Lead 调整汇总表恰当性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险",
            k1_ref="lead-qc-rules 模块6; MT-003",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="LLM：direct 金额勾稽、indirect 跨科目闭环；cross_account_policy=flag_not_fail。",
        ),
        RuleSpec(
            dict_code="LEAD-007",
            rule_id="lead_movement_rows_complete",
            rule_name="Lead 引导表四行与核心列",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="lead-qc-rules 模块4",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-008",
            rule_id="lead_movement_consistency",
            rule_name="Lead 引导表变动额自洽",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="lead-qc-rules 模块4",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="LEAD-009",
            rule_id="lead_movement_notes_required",
            rule_name="Lead 须调查行须有Notes",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="lead-qc-rules 模块4",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="AE-002",
            rule_id="risk_threshold_consistency",
            rule_name="各认定CRA正确性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第6条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="摘录认定 CRA/TT 至报告；简版 no_cra_te_volatility 跳过；人工与 Canvas 核对",
        ),
        RuleSpec(
            dict_code="AE-003",
            rule_id="psp_completion",
            rule_name="PSP程序执行完整性",
            procedure_code="SUMMARY",
            sheet_hints=("所有工作表", "汇总"),
            sheet_kinds=("summary",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第7条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="不执行且无理由→FAIL；执行为是时勾稽工作簿 sheet（名称规范化/模糊匹配/表头非空密度 WARN）",
        ),
        RuleSpec(
            dict_code="AE-004",
            rule_id="unexpected_movement_investigation",
            rule_name="异常波动调查充分性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="No-考虑到影响不重要",
            k1_ref="K1 CheckList 第8条",
            manual_priority="P3-后续扩展",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="M2 确定性子集：超门槛或调查=是时波动说明不得为空/仅无异常波动",
        ),
        RuleSpec(
            dict_code="AE-005",
            rule_id="workpaper_cleanliness",
            rule_name="底稿清洁度",
            procedure_code="GLOBAL",
            sheet_hints=("所有工作表",),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.WARN,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="No-考虑到影响不重要",
            k1_ref="K1 CheckList 第9条",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="AE-006",
            rule_id="workpaper_index_accuracy",
            rule_name="底稿索引准确性",
            procedure_code="GLOBAL",
            sheet_hints=("所有工作表",),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第10条",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        # --- 错报 ---
        RuleSpec(
            dict_code="MT-001",
            rule_id="fixed_asset_definition",
            rule_name="固定资产定义符合性",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险",
            k1_ref="K1 CheckList 第11条",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="MT-002",
            rule_id="special_movement_identification",
            rule_name="特殊性质变动识别",
            procedure_code="K.02",
            sheet_hints=("K.02.1", "K.02.2", "新增清单", "处置清单"),
            sheet_kinds=("addition_list", "disposal_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第12条",
            manual_priority="P3-后续扩展",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="MT-003",
            rule_id="adjustment_testing",
            rule_name="调整事项测试恰当性",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet", "A3A5"),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险",
            k1_ref="K1 CheckList 第13条",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        # --- 基础程序 / 核对 ---
        RuleSpec(
            dict_code="LEAD-011",
            rule_id="lead_check_with_a3_row",
            rule_name="Lead Check with A3 核对",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="lead-qc-rules 模块4.4",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Diff 非零须 Notes；引导表金额与 Check with A3 行不一致为 WARN",
        ),
        RuleSpec(
            dict_code="LEAD-010",
            rule_id="lead_rollforward_tb_reconciliation",
            rule_name="Lead 引导表与K.01后推核对",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet", "K.01"),
            sheet_kinds=("lead", "rollforward"),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="lead-qc-rules 模块4.6",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="有 K.01 时比对期末账面数与后推合计；无后推则跳过",
        ),
        RuleSpec(
            dict_code="GL-001",
            rule_id="lead_tb_reconciliation",
            rule_name="期末账面数与TB核对",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead", "rollforward"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第14条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="GL-002",
            rule_id="rollforward_fa_list_reconciliation",
            rule_name="期末账面数与FA list核对",
            procedure_code="K.01",
            sheet_hints=("K.00 Lead Sheet", "K.01 Agree SL to GL", "FA list"),
            sheet_kinds=("rollforward", "fa_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第14条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="主检查读取 K.01 表3 check 结果；差异为0或不超过SAD通过，超过SAD且无Notes为FAIL；表2 SUMIF 汇总作辅助；Agent 自算仅作兜底提示",
        ),
        RuleSpec(
            dict_code="GL-003",
            rule_id="lead_prior_year_reconciliation",
            rule_name="期初期末审定数与Lead核对",
            procedure_code="K.00",
            sheet_hints=("K.00 Lead Sheet",),
            sheet_kinds=("lead",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第15条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="GL-004",
            rule_id="rollforward_depreciation_pl_reconciliation",
            rule_name="折旧费用与利润表核对",
            procedure_code="K.01",
            sheet_hints=("K.01 Agree SL to GL", "K.00 Lead Sheet"),
            sheet_kinds=("rollforward", "lead"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="No-考虑到影响不重要",
            k1_ref="K1 CheckList 第16条",
            manual_priority="P1-最高优先级",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="K.01 表4折旧费用与利润表科目核对：差异=0或≤SAD通过，>SAD无Notes为FAIL。",
        ),
        RuleSpec(
            dict_code="GL-005",
            rule_id="rollforward_abnormal_amounts",
            rule_name="后推表异常金额识别",
            procedure_code="K.01",
            sheet_hints=("K.01 Agree SL to GL", "FA list"),
            sheet_kinds=("rollforward", "fa_list"),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.01 / SOP K1.01 易错点【01】",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="累折>原值、负净值等；见 planning/k01-six-block-qc-matrix",
        ),
        RuleSpec(
            dict_code="GL-006",
            rule_id="rollforward_exists",
            rule_name="后推明细表存在",
            procedure_code="K.01",
            sheet_hints=("K.01 Agree SL to GL",),
            sheet_kinds=("rollforward",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.01 §三",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="GL-007",
            rule_id="rollforward_columns_complete",
            rule_name="后推金额列完整（L1）",
            procedure_code="K.01",
            sheet_hints=("K.01 Agree SL to GL",),
            sheet_kinds=("rollforward",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.01 §三；L1 见 k01-workpaper-layouts",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="GL-008",
            rule_id="rollforward_difference_over_sad",
            rule_name="K.01 TB差异超过SAD调查",
            procedure_code="K.01",
            sheet_hints=("K.00 Lead Sheet", "K.01 Agree SL to GL"),
            sheet_kinds=("lead", "rollforward"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.01 §三；SOP K1.01【02】差异调查",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="K.01 TB check 差异超过 Lead SAD 时检查 Notes；有 Notes 输出 NEED_REVIEW，无 Notes 输出 FAIL",
        ),
        RuleSpec(
            dict_code="GL-009",
            rule_id="rollforward_notes_semantic",
            rule_name="K.01 差异调查 Notes 恰当性",
            procedure_code="K.01",
            sheet_hints=("K.00 Lead Sheet", "K.01 Agree SL to GL"),
            sheet_kinds=("lead", "rollforward"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.01 §三；SOP K1.01【02】差异调查",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="LLM 分专题复核 TB/表3/表4 Notes；仅在材料差异>SAD 且已有 Notes 时触发；不将 FAIL 改为 PASS",
        ),
        # --- FA list 数据质量（qc-checklist 补充，字典待增行）---
        RuleSpec(
            dict_code="FA-RC-001",
            rule_id="fa_list_required_fields",
            rule_name="FA list 必需字段完整",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-002",
            rule_id="unique_asset_id",
            rule_name="资产编号唯一",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-003",
            rule_id="asset_value_consistency",
            rule_name="金额勾稽一致",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-004",
            rule_id="asset_amount_non_negative",
            rule_name="金额非负",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-005",
            rule_id="useful_life_positive",
            rule_name="使用寿命为正",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-006",
            rule_id="salvage_rate_range",
            rule_name="残值率区间合理",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="FA-RC-007",
            rule_id="asset_start_date_reasonable",
            rule_name="入账日期合理",
            procedure_code="FA_LIST",
            sheet_hints=("FA list",),
            sheet_kinds=("fa_list",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist FA List",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.PLANNED,
        ),
        # --- 抽样与测试（节选，完整见 docs/rule-dictionary-mapping.md）---
        RuleSpec(
            dict_code="SP-001",
            rule_id="addition_population_homogeneity",
            rule_name="交易类别区分",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.2"),
            sheet_kinds=("addition_list", "disposal_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第19条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="K02-003",
            rule_id="addition_required_fields",
            rule_name="新增清单字段完整",
            procedure_code="K.02.1",
            sheet_hints=("新增清单",),
            sheet_kinds=("addition_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.1 新增清单字段",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="检查新增清单必需字段：类别、编号、名称、入账开始日期、原值、新增方式。",
        ),
        RuleSpec(
            dict_code="K02-001",
            rule_id="addition_test_package_complete",
            rule_name="新增测试程序包完整",
            procedure_code="K.02.1",
            sheet_hints=("新增清单", "K.02.1 新增测试", "K.02.1a 新增选样输出"),
            sheet_kinds=("addition_list",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K.02.1 新增测试程序包",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="汇总页标记已执行时检查三表链条；汇总拒绝执行则不查。缺表为 NEED_REVIEW 结构提示，不等于程序未执行；若测试底稿/汇总有受限执行说明则提示一致性复核。",
        ),
        RuleSpec(
            dict_code="SP-002",
            rule_id="addition_rollforward_reconciliation",
            rule_name="样本池与BKD一致性",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.2", "新增清单"),
            sheet_kinds=("addition_list", "rollforward"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第19条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="新增清单购置原值合计 vs K.01 后推购置行；差异超过 SAD 时在 message 中提示调查。",
        ),
        RuleSpec(
            dict_code="SP-003",
            rule_id="sampling_parameters",
            rule_name="抽样工具参数设置",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.2"),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第20条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="SP-004",
            rule_id="key_item_selection",
            rule_name="关键项选取恰当性",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.2"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第21条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.PLANNED,
        ),
        RuleSpec(
            dict_code="AT-001",
            rule_id="addition_sample_match",
            rule_name="测试样本与抽样输出一致",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第23条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="检查 K.02.1a 已选样本与 K.02.1 实测样本的一致性，并附带关键项金额、证据金额和异常说明摘录。",
        ),
        RuleSpec(
            dict_code="AT-002",
            rule_id="addition_sample_pool_purchase_amount_match",
            rule_name="抽样样本池金额与购置总体一致",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1a", "新增清单"),
            sheet_kinds=("addition_sample_output", "addition_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第33条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="核对 K.02.1a 样本池总体金额是否等于新增清单购置/外购新增金额。",
        ),
        RuleSpec(
            dict_code="AT-003",
            rule_id="addition_sampling_te_cra_consistency",
            rule_name="抽样参数 TE/CRA 与 Lead 一致",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1a", "K.00 Lead Sheet"),
            sheet_kinds=("addition_sample_output", "lead"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第5-6条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="核对 Skywind 抽样 TE 和综合风险评估；CRA 需将中文最低/低/中/高映射到 Lead 英文 Minimal/Low/Moderate/High。",
        ),
        RuleSpec(
            dict_code="AT-004",
            rule_id="addition_sampling_assertions_scope",
            rule_name="新增抽样测试认定范围",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1a",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第33条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="一般新增 TOD 从账面记录追查支持性证据，不应默认包含完整性认定；如包含完整性，提示人工复核。",
        ),
        RuleSpec(
            dict_code="AT-005",
            rule_id="addition_sample_replacement_reason",
            rule_name="新增测试替换样本原因",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.1a"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第33条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="替换样本仅应在原正常样本无法使用时启用，例如自动结转凭证不代表实际事项；无原因说明时提示复核。",
        ),
        RuleSpec(
            dict_code="AT-006",
            rule_id="addition_supporting_documentation",
            rule_name="支持性文件充分性",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第24条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
            notes="K1：合同/控制权转移单据编号不强制；Agent 仅宜做空白/form 检查",
        ),
        RuleSpec(
            dict_code="AT-007",
            rule_id="addition_special_nature_testing",
            rule_name="特殊性质新增测试",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "新增清单"),
            sheet_kinds=("addition_list",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第25条",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="AT-008",
            rule_id="addition_exception_followup",
            rule_name="例外情况跟进记录",
            procedure_code="K.02.1",
            sheet_hints=("K.02.1",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第26条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.PLANNED,
        ),
        RuleSpec(
            dict_code="AT-LLM-001",
            rule_id="addition_semantic_review",
            rule_name='新增测试语义复核',
            procedure_code="K.02.1",
            sheet_hints=("K.02.1", "K.02.1a"),
            sheet_kinds=("addition_test", "addition_sample_output"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='基础程序',
            reviewer_role="reviewer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第24/26条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing LLM conditional rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DT-P0-001",
            rule_id="disposal_reconciliation_readability",
            rule_name="处置总体核对模块可读性",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 处置清单核对",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P0-002",
            rule_id="disposal_reconciliation_formula_source",
            rule_name="处置总体核对公式来源",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2", "处置清单", "K.01"),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 处置清单核对",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P0-003",
            rule_id="disposal_net_value_recalculation",
            rule_name="处置总体净值重算",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="qc-checklist K.02.2 处置清单核对",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P0-004",
            rule_id="disposal_rollforward_reconciliation",
            rule_name="处置清单与后推金额勾稽",
            procedure_code="K.02.2",
            sheet_hints=("处置清单", "K.02.2", "K.01"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 处置清单核对",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P0-005",
            rule_id="disposal_difference_investigation",
            rule_name="处置勾稽差异调查",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 差异超过 SAD",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P0-006",
            rule_id="disposal_required_fields",
            rule_name="处置清单必需字段完整",
            procedure_code="K.02.2",
            sheet_hints=("处置清单",),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 处置清单字段完整",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="净值列允许缺失；原值、累计折旧和减值准备用于重新计算净值。",
        ),
        RuleSpec(
            dict_code="DT-P0-007",
            rule_id="disposal_list_net_value_recalculation",
            rule_name="处置清单净值重算",
            procedure_code="K.02.2",
            sheet_hints=("处置清单",),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="qc-checklist K.02.2 处置清单字段完整",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P1-001",
            rule_id="disposal_method_classification",
            rule_name="处置减少方式分类",
            procedure_code="K.02.2",
            sheet_hints=("处置清单",),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="qc-checklist K.02.2 处置总体同质性",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P1-002",
            rule_id="disposal_other_reduction_over_tt",
            rule_name="重大其他减少单独复核",
            procedure_code="K.02.2",
            sheet_hints=("处置清单",),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="底稿范围、程序设计",
            reviewer_role="reviewer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="qc-checklist K.02.2 处置总体同质性",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-001",
            rule_id="disposal_sample_pool_amount_match",
            rule_name="处置样本池总体金额一致",
            procedure_code="K.02.2",
            sheet_hints=("处置清单", "K.02.2a"),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第28条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-002",
            rule_id="disposal_sampling_te_cra_consistency",
            rule_name="处置选样 TE/CRA 一致",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2a", "K.00"),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="底稿范围、程序设计",
            reviewer_role="preparer",
            qc_checkpoint="Y-影响程序范围、证据程度",
            k1_ref="K1 CheckList 第28条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-003",
            rule_id="disposal_sample_replacement_reason",
            rule_name="处置替换样本原因",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2", "K.02.2a"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第28条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-004",
            rule_id="disposal_test_attributes_complete",
            rule_name="处置三个测试属性完整",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第29条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-005",
            rule_id="disposal_test_amount_recalculation",
            rule_name="处置测试金额重算",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第29条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-P2-006",
            rule_id="disposal_sale_evidence_complete",
            rule_name="出售样本证据记录完整",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第29条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-004",
            rule_id="disposal_exception_followup",
            rule_name="处置例外情况跟进记录",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第29条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DT-LLM-001",
            rule_id="disposal_semantic_review",
            rule_name="处置测试语义复核",
            procedure_code="K.02.2",
            sheet_hints=("处置清单", "K.02.2", "K.02.2a"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第28-29条",
            agent_priority=AgentPriority.P2,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="仅复核文字说明充分性，不计算金额，不覆盖确定性规则。",
        ),
        RuleSpec(
            dict_code="DT-001",
            rule_id="disposal_sample_match",
            rule_name="测试样本与抽样输出一致",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第28条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="检查 K.02.2a 已选处置样本与 K.02.2 实测样本的资产编号、净值和样本类型一致性；替换样本作为备选样本，不强制要求进入实测。",
        ),
        RuleSpec(
            dict_code="K02-002",
            rule_id="disposal_test_package_complete",
            rule_name="处置测试程序包完整",
            procedure_code="K.02.2",
            sheet_hints=("处置清单", "K.02.2 处置测试", "K.02.2a 处置选样输出"),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K.02.2 处置测试程序包",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="汇总页标记已执行时检查三表链条；汇总拒绝执行则不查。缺表为 NEED_REVIEW 结构提示，不等于程序未执行；若测试底稿/汇总有受限执行说明则提示一致性复核。",
        ),
        RuleSpec(
            dict_code="DT-002",
            rule_id="disposal_supporting_documentation",
            rule_name="支持性文件充分性",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-审计基础程序",
            k1_ref="K1 CheckList 第29条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="DT-003",
            rule_id="disposal_special_nature_testing",
            rule_name="特殊性质减少测试",
            procedure_code="K.02.2",
            sheet_hints=("K.02.2", "处置清单"),
            sheet_kinds=("disposal_list",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第30条",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="DP-001",
            rule_id="depreciation_policy_change",
            rule_name="折旧政策变化识别",
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.WARN,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第33条",
            manual_priority="P3-后续扩展",
            agent_priority=AgentPriority.P4,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="DP-POL-001",
            rule_id="k03_policy_three_elements_complete",
            rule_name='折旧政策三要素完整性',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 policy precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-002",
            rule_id="k03_policy_method_change_consistency",
            rule_name='折旧方法变更一致性',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 policy precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-003",
            rule_id="k03_policy_annual_rate_recalculation",
            rule_name='年折旧率重新计算',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='错报',
            reviewer_role="preparer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-004",
            rule_id="k03_policy_period_consistency",
            rule_name='本期与上期政策一致性',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='错报',
            reviewer_role="preparer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-005",
            rule_id="k03_policy_change_field_explanation",
            rule_name='政策变更字段说明',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='基础程序',
            reviewer_role="preparer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-006",
            rule_id="k03_policy_fa_category_coverage",
            rule_name='FA list 类别政策覆盖',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "FA list"),
            sheet_kinds=("depreciation_policy", "fa_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='错报',
            reviewer_role="preparer",
            qc_checkpoint='No-非PSP程序要求',
            k1_ref='K1 CheckList 第34条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-007",
            rule_id="k03_policy_fa_life_exception_followup",
            rule_name='FA list 使用寿命例外跟进',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "FA list"),
            sheet_kinds=("depreciation_policy", "fa_list"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category='错报',
            reviewer_role="preparer",
            qc_checkpoint='No-非PSP程序要求',
            k1_ref='K1 CheckList 第34条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-008",
            rule_id="k03_policy_fa_salvage_exception_followup",
            rule_name='FA list 残值率例外跟进',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "FA list"),
            sheet_kinds=("depreciation_policy", "fa_list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='基础程序',
            reviewer_role="preparer",
            qc_checkpoint='No-非PSP程序要求',
            k1_ref='K1 CheckList 第34条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-POL-009",
            rule_id="k03_policy_conclusion_consistency",
            rule_name='折旧政策复核结论一致性',
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "折旧政策复核"),
            sheet_kinds=("depreciation_policy",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='错报',
            reviewer_role="preparer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第33条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 policy runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-CTRL-001",
            rule_id="k03_program_execution_consistency",
            rule_name="K.03 汇总勾选与实际执行一致性",
            procedure_code="K.03",
            sheet_hints=("汇总", "K.03.1", "K.03.2", "K.03.3"),
            sheet_kinds=("summary", "sap", "depreciation_tod", "depreciation_policy"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="No-非PSP程序要求",
            k1_ref="K1 CheckList 第33-35条",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Compare summary selections with EXECUTED K03ExecutionProfile components; policy is assessed independently.",
        ),
        RuleSpec(
            dict_code="DP-CTRL-002",
            rule_id="k03_depreciation_path_identified",
            rule_name="K.03 折旧测试执行路径已识别",
            procedure_code="K.03",
            sheet_hints=("汇总", "K.03.1", "K.03.2"),
            sheet_kinds=("summary", "sap", "depreciation_tod"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="No-非PSP程序要求",
            k1_ref="K1 CheckList 第35条",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Require at least one EXECUTED SAP or TOD component when the summary selects a depreciation test.",
        ),
        RuleSpec(
            dict_code="DP-CTRL-003",
            rule_id="k03_path_combination_consistency",
            rule_name="K.03 折旧测试路径组合一致性",
            procedure_code="K.03",
            sheet_hints=("K.03.1", "K.03.2"),
            sheet_kinds=("sap", "depreciation_tod"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="No-非PSP程序要求",
            k1_ref="K1 CheckList 第35条",
            agent_priority=AgentPriority.P1,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Allow one SAP plus one TOD path; flag duplicate, dual-SAP, or dual-TOD executed paths for review.",
        ),
        RuleSpec(
            dict_code="DP-002",
            rule_id="depreciation_policy_list_consistency",
            rule_name="折旧政策与清单一致性",
            procedure_code="K.03.3",
            sheet_hints=("K.03.3", "FA list"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="No-非PSP程序要求",
            k1_ref="K1 CheckList 第34条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.PLANNED,
        ),
        RuleSpec(
            dict_code="DP-003",
            rule_id="sap_precision_selection",
            rule_name="折旧测试策略恰当性",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1", "K.03.2"),
            sheet_kinds=("sap", "depreciation_tod"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第35条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DP-SAP-001",
            rule_id="sap_te_consistency",
            rule_name="SAP 可容忍误差与 Lead 一致性",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1 SAP", "K.00 Lead Sheet"),
            sheet_kinds=("sap", "lead"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第35条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DP-SAP-002",
            rule_id="sap_high_cra_consistency",
            rule_name="高精度 SAP CRA 与 Lead V/M 一致性",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1 SAP-高精确度", "K.00 Lead Sheet"),
            sheet_kinds=("sap", "lead"),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第35条",
            manual_priority="P2-高优先级",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DP-004",
            rule_id="sap_depreciation_difference",
            rule_name="SAP折旧测试差异处理",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1 SAP",),
            sheet_kinds=("sap",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第36条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DP-SAP-003",
            rule_id="sap_medium_category_deviation_explanation",
            rule_name="中精度 SAP 类别及合计偏差说明",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1 SAP-中精确度", "Notes"),
            sheet_kinds=("sap",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第36条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="逐类别及合计比较偏差阈值；超阈值时检查同列 Notes 索引和说明存在性，充分性由人工复核。",
        ),
        RuleSpec(
            dict_code="DP-SAP-004",
            rule_id="sap_high_category_deviation_explanation",
            rule_name="高精度 SAP 类别偏差说明",
            procedure_code="K.03.1",
            sheet_hints=("K.03.1 SAP-高精确度", "已分配偏差阈值", "Notes"),
            sheet_kinds=("sap",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第36条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="逐类别比较差异和已分配偏差阈值；超阈值时检查对应 Notes 存在性，充分性由人工复核。",
        ),
        RuleSpec(
            dict_code="DP-005",
            rule_id="depreciation_by_item_sad",
            rule_name="By Item折旧测试差异",
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category="错报",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第37条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.PLANNED,
        ),
        RuleSpec(
            dict_code="DP-006",
            rule_id="depreciation_tod_sampling",
            rule_name="TOD抽样折旧测试抽样过程",
            procedure_code="K.03.2",
            sheet_hints=("K.03.2 TOD",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.WARN,
            problem_category="基础程序",
            reviewer_role="preparer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第38条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        *[
            RuleSpec(
                dict_code=dict_code,
                rule_id=rule_id,
                rule_name=rule_name,
                procedure_code="K.03.2",
                sheet_hints=("K.03.2 TOD", "K.03.2a 折旧选样输出"),
                sheet_kinds=("depreciation_tod",),
                automation=automation,
                default_severity=severity,
                problem_category="基础程序" if automation == AutomationLevel.REVIEW else "错报",
                reviewer_role="preparer",
                qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
                k1_ref="K1 CheckList 第38条",
                agent_priority=AgentPriority.P3,
                implementation=ImplementationStatus.IMPLEMENTED,
                notes="DP-006/DP-007 的 TOD 抽样 Agent 可执行子规则。",
            )
            for dict_code, rule_id, rule_name, automation, severity in (
                ("DP-TOD-PRE-001", "k03_tod_sampling_output_required", "TOD 抽样选样输出配套", AutomationLevel.REVIEW, Severity.NEED_REVIEW),
                ("DP-TOD-001", "k03_tod_sampling_currency", "TOD 抽样货币单元", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-002", "k03_tod_sampling_te_consistency", "TOD 选样 TE 与 Lead 一致性", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-003", "k03_tod_sampling_population_reconciliation", "TOD 抽样总体与 K.01 勾稽", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-004", "k03_tod_sampling_count_consistency", "TOD 选样数量一致性", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-005", "k03_tod_sampling_identity_consistency", "TOD 样本编号一致性", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-006", "k03_tod_sampling_attributes", "TOD 样本测试属性完整性", AutomationLevel.REVIEW, Severity.NEED_REVIEW),
                ("DP-TOD-007", "k03_tod_sampling_difference_followup", "TOD 样本差异跟进", AutomationLevel.AUTO_FAIL, Severity.FAIL),
                ("DP-TOD-008", "k03_tod_sampling_documentation", "TOD 关键项目依据与测试结论", AutomationLevel.REVIEW, Severity.NEED_REVIEW),
            )
        ],
        RuleSpec(
            dict_code="DP-BI-PRE-001",
            rule_id="k03_tod_by_item_detail_unreadable",
            rule_name='by-item 折旧明细读取质量',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 by-item precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-PRE-002",
            rule_id="k03_tod_by_item_required_fields",
            rule_name='by-item 折旧必需字段完整',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 by-item precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-PRE-003",
            rule_id="k03_tod_by_item_difference_column",
            rule_name='by-item 折旧差异列检查',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 by-item precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-PRE-004",
            rule_id="k03_tod_by_item_sad_unavailable",
            rule_name='by-item 折旧测试 SAD 可用性',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_FAIL,
            default_severity=Severity.FAIL,
            problem_category='底稿可读性',
            reviewer_role="preparer",
            qc_checkpoint='Y-审计基础程序',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 by-item precondition rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-001",
            rule_id="k03_tod_by_item_difference_over_sad",
            rule_name='by-item 折旧差异超过 SAD',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category='错报',
            reviewer_role="reviewer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 by-item runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-002",
            rule_id="k03_tod_by_item_total_difference_over_sad",
            rule_name='by-item 折旧总体差异超过 SAD',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category='错报',
            reviewer_role="reviewer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 by-item runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-003",
            rule_id="k03_tod_by_item_conclusion_missing",
            rule_name='by-item 折旧测试说明记录',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item"),
            sheet_kinds=("depreciation_tod",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.NEED_REVIEW,
            problem_category='错报',
            reviewer_role="reviewer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register existing K.03 by-item runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-BI-004",
            rule_id="k03_tod_by_item_rollforward_depreciation",
            rule_name='by-item 折旧与 K.01 后推勾稽',
            procedure_code="K.03.2",
            sheet_hints=("K.03.2", "by item", "K.01"),
            sheet_kinds=("depreciation_tod", "rollforward"),
            automation=AutomationLevel.AUTO_WARN,
            default_severity=Severity.WARN,
            problem_category='错报',
            reviewer_role="reviewer",
            qc_checkpoint='Y-错报风险-假设不是所有底稿都涉及',
            k1_ref='K1 CheckList 第37条',
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
            notes="Register observed K.03 by-item runner rule; no rule logic change.",
        ),
        RuleSpec(
            dict_code="DP-007",
            rule_id="depreciation_tod_difference",
            rule_name="TOD抽样折旧测试差异",
            procedure_code="K.03.2",
            sheet_hints=("K.03.2 TOD",),
            automation=AutomationLevel.REVIEW,
            default_severity=Severity.FAIL,
            problem_category="基础程序",
            reviewer_role="reviewer",
            qc_checkpoint="Y-错报风险-假设不是所有底稿都涉及",
            k1_ref="K1 CheckList 第39条",
            agent_priority=AgentPriority.P3,
            implementation=ImplementationStatus.IMPLEMENTED,
        ),
        RuleSpec(
            dict_code="DL-001",
            rule_id="first_delivery_standard",
            rule_name="首次交付标准",
            procedure_code="GLOBAL",
            sheet_hints=("所有工作表",),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.FAIL,
            problem_category="交付风险",
            reviewer_role="preparer",
            qc_checkpoint="Y-交付风险",
            k1_ref="K1 CheckList 第45条",
            manual_priority="P3-后续扩展",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
        RuleSpec(
            dict_code="DL-002",
            rule_id="final_delivery_standard",
            rule_name="整体交付标准",
            procedure_code="GLOBAL",
            sheet_hints=("所有工作表",),
            automation=AutomationLevel.MANUAL_ONLY,
            default_severity=Severity.FAIL,
            problem_category="交付风险",
            reviewer_role="preparer",
            qc_checkpoint="Y-交付风险",
            k1_ref="K1 CheckList 第48条",
            agent_priority=AgentPriority.MANUAL,
            implementation=ImplementationStatus.MANUAL_ONLY,
        ),
    ]


_REGISTRY: dict[str, RuleSpec] = {}
_RULE_ID_INDEX: dict[str, RuleSpec] = {}


def _build_index() -> None:
    if _REGISTRY:
        return
    for spec in _specs():
        _REGISTRY[spec.dict_code] = spec
        _RULE_ID_INDEX[spec.rule_id] = spec


def all_specs() -> list[RuleSpec]:
    _build_index()
    return list(_REGISTRY.values())


def get_by_dict_code(code: str) -> RuleSpec | None:
    _build_index()
    return _REGISTRY.get(code)


def get_by_rule_id(rule_id: str) -> RuleSpec | None:
    _build_index()
    return _RULE_ID_INDEX.get(rule_id)


def iter_by_agent_priority(priority: AgentPriority) -> Iterator[RuleSpec]:
    for spec in all_specs():
        if spec.agent_priority == priority:
            yield spec


def iter_implemented() -> Iterator[RuleSpec]:
    for spec in all_specs():
        if spec.implementation == ImplementationStatus.IMPLEMENTED:
            yield spec


def attach_rule_metadata(issues: list[QcIssue]) -> list[QcIssue]:
    """为 issues 附加规则字典元数据（按 rule_id 查找）。"""
    for issue in issues:
        spec = get_by_rule_id(issue.rule_id)
        if spec:
            spec.enrich_issue(issue)
    return issues
